version: '2'
services:
    ifirma-app:
        image: ifirma
        external_links:
            - ifirma-mysql:mysql
            - ifirma-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ifirma?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    ifirma-mysql:
        extends:
            file: mysql.yml
            service: ifirma-mysql
    ifirma-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ifirma-elasticsearch
